export enum DomainErrorCodes {
  INVALID_INPUT = "INVALID_INPUT",
  ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND",
  UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS",
  SYSTEM_ERROR = "SYSTEM_ERROR",
  DUPLICATE_ENTITY = "DUPLICATE_ENTITY",
}
